[test]
root = "./packages/testing"
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "**/packages/testing/src/**",
  "**/packages/testing/test/helpers/**"
]
